<?xml version="1.0" encoding="UTF-8" ?>

<project xmlns="http://maven.apache.org/POM/4.0.0">

  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.io7m.primogenitor</groupId>
    <artifactId>com.io7m.primogenitor.full</artifactId>
    <version>8.4.0</version>
  </parent>

  <groupId>com.io7m.shaml</groupId>
  <artifactId>com.io7m.shaml</artifactId>
  <version>0.0.1-SNAPSHOT</version>

  <packaging>pom</packaging>
  <name>com.io7m.shaml</name>
  <description>I Wish I Was A SAML Server</description>
  <url>https://www.github.com/io7m/shaml/</url>

  <properties>
    <!-- Configuration -->
    <io7m.api.previousVersion>0.0.1-SNAPSHOT</io7m.api.previousVersion>
    <io7m.java.targetJavaVersion>21</io7m.java.targetJavaVersion>

    <!-- Third-party dependencies. -->
    <org.junit.version>5.12.1</org.junit.version>
    <io.helidon.version>4.2.0</io.helidon.version>
    <com.fasterxml.jackson.version>2.18.3</com.fasterxml.jackson.version>

    <!-- https://hub.docker.com/_/alpine/ -->
    <com.io7m.oci.versionAlpine>3.21.3</com.io7m.oci.versionAlpine>
    <!-- https://hub.docker.com/_/eclipse-temurin -->
    <com.io7m.oci.versionTemurin>24_36-jre-alpine-3.21</com.io7m.oci.versionTemurin>
  </properties>

  <modules>
    <module>com.io7m.shaml.server</module>
    <module>com.io7m.shaml.oci</module>
  </modules>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.helidon</groupId>
        <artifactId>helidon-bom</artifactId>
        <version>${io.helidon.version}</version>
        <scope>import</scope>
        <type>pom</type>
      </dependency>

      <dependency>
        <groupId>org.junit</groupId>
        <artifactId>junit-bom</artifactId>
        <version>${org.junit.version}</version>
        <scope>import</scope>
        <type>pom</type>
      </dependency>

      <dependency>
        <groupId>com.fasterxml.jackson</groupId>
        <artifactId>jackson-bom</artifactId>
        <version>${com.fasterxml.jackson.version}</version>
        <scope>import</scope>
        <type>pom</type>
      </dependency>

      <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-bom</artifactId>
        <version>2.0.17</version>
        <scope>import</scope>
        <type>pom</type>
      </dependency>

      <dependency>
        <groupId>org.freemarker</groupId>
        <artifactId>freemarker</artifactId>
        <version>2.3.34</version>
      </dependency>

      <dependency>
        <groupId>ch.qos.logback</groupId>
        <artifactId>logback-classic</artifactId>
        <version>1.5.18</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-checkstyle-plugin</artifactId>
          <configuration>
            <suppressionsLocation>checkstyle-filter.xml</suppressionsLocation>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>

</project>
